apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: github-demo-ollama
spec:
  href: 'https://github.com/redhat-na-ssa/demo-ollama'
  location: ApplicationMenu
  text: GitHub - Demo Ollama
  applicationMenu:
    section: Git Repos
    imageURL: /static/assets/public/imgs/logos/github.svg
