apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: ollama

commonlabels:
  app: ollama

resources:
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - route.yaml
  - svc.yaml
